
server:
    error:
        include-stacktrace: on-param

spring:
    datasource:
        # url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
        # username: root
        # password: root
        url: jdbc:postgresql://localhost:5432/anime
        username: postgres
        password: postgres
        
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            hibernnate:
                SQL: DEBUG